---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-symlinks

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: Check Git rules via gitlint
        args: [-v, --ignore=body-is-missing, --msg-filename]
